### ISSUE TITLE
Cool app!

### ISSUE THREAD

**Issue by zeke** [sidneys/desktop-dimmer#1]
You should submit it to https://github.com/electron/electron-apps

🌔

**Comment by sidneys** [comment]
@zeke Thanks a lot for the feedback! It's currently in testing, no major testing has been done. Are there any major impediments which should be addressed before taking it out of "prerelease"? Cheers.

**Comment by zeke** [comment]
A few observations:

When I clicked this "quit" button, I didn't know what behavior to expect:

![screen shot 2016-12-22 at 3 43 35 pm](https://cloud.githubusercontent.com/assets/2289/21443926/995750e2-c85d-11e6-9273-607770767990.png)

Maybe something like an [X] would be more universally recognizable.

Also for some reason, Spotlight (on macOS Sierra) is not finding the app when I search for it, even though it's installed in /Applications:

![screen shot 2016-12-22 at 3 46 49 pm](https://cloud.githubusercontent.com/assets/2289/21443968/e1304694-c85d-11e6-9d13-21f06abda5ee.png)

Is this app [code-signed](https://github.com/electron-userland/electron-builder/wiki/Code-Signing)? Maybe Spotlight doesn't index apps that are not signed.

**Comment by zeke** [comment]
PS the thing I like most about this app is its minimalism. It does one thing!

[small sharp tools](https://www.brandur.org/small-sharp-tools) ftw.

**Comment by sidneys** [comment]
@zeke 
v1.9.0 Has that new close button, apart from other improvements. Happy new year😎

@Codesigning: Not yet, but it is on the roadmap. Not sure why Spotlight did not catch it.

**Comment by zeke** [comment]
> Happy new year

🍰
