### ISSUE TITLE
Dimming is one pixel off

### ISSUE THREAD

**Issue by romainrichard** [sidneys/desktop-dimmer#11]
Observing this issue on Ubuntu 16.04.2, not sure if it affects other versions.

When Desktop Dimmer is running, it dims the whole screen but a one-pixel row at the bottom of the screen and a one-pixel column at the right of the screen.

Here's a screenshot of the bottom right of my screen as proof, obviously you'll need to zoom in a lot to see that off-by-one pixel issue.
![desktop dimmer pixel off](https://cloud.githubusercontent.com/assets/498307/23495599/7c1f1e9a-fece-11e6-862a-4a0b20b47383.png)

This is only noticeable when the alpha value is turned way up and the one-pixel column/row is bright (white for example), the rest of the time it's barely noticeable.

**Comment by sidneys** [comment]
@romainrichard 
This should be fixed in the latest [v2.8.1](https://github.com/sidneys/desktop-dimmer/releases). Please share your findings. Cheers.

**Comment by romainrichard** [comment]
It is fixed, thanks!
