### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by Nekromancer** [sidneys/desktop-dimmer#12]
App is great, it's doing what it's supposed to do. But when i look a this:

![http://i.imgur.com/LzM0IdL.png](http://i.imgur.com/LzM0IdL.png)

It makes me question this quote from your readme:

> Small resource footprint, minimal User Interface.

Don't take it as offence, i know electron have it's rights and a lot of people have enough memory to run it. But it's kinda unfair if you advertise `small resource footprint` when it's just.. not.

This kind of software, if written in something native, could take 0,5 MB of ram? I think we can go even lower than this.

**Comment by Sytten** [comment]
Well its running a full chrome +nodejs under the hood, can't really expect to take less than 500mb of ram...

**Comment by Nekromancer** [comment]
I know WHY it's the case. I'm just pointing out that it's unfair to advertise it with small resource label ;-)

**Comment by sidneys** [comment]
@Sytten @Nekromancer 
Thanks for your comments and the heads-up on resource usage on Windows. We'll continue trying to keep the resources required to a minimum (and this is still a beta), but are restricted by what Electron provides as overhead.
