### ISSUE TITLE
Menus, tooltips and cursor are not dimmed

### ISSUE THREAD

**Issue by romainrichard** [sidneys/desktop-dimmer#13]
Using version 2.7.3 on Ubuntu 16.04.

While windows get dimmed, any menu or tooltip doesn't. Below are some examples:

![menus1](https://cloud.githubusercontent.com/assets/498307/23576669/83e83ef2-0060-11e7-94a4-20065d794e01.png)
![menus2](https://cloud.githubusercontent.com/assets/498307/23576670/8759a026-0060-11e7-9586-bda8e5863636.png)
![menus3](https://cloud.githubusercontent.com/assets/498307/23576679/b7666056-0060-11e7-8099-a1814529b4ff.png)
![menus4](https://cloud.githubusercontent.com/assets/498307/23576781/c5b3eafe-0063-11e7-93ab-dcfbedb6a1e3.png)

**Comment by sidneys** [comment]
@romainrichard 
This is a general issue with upstream Electron, as testing has shown. Thus, for the time being, this will remain a 'wontfix'.
