### ISSUE TITLE
Add ability to pause Desktop Dimmer

### ISSUE THREAD

**Issue by romainrichard** [sidneys/desktop-dimmer#14]
Currently, if we want to temporarily disable Desktop Dimmer, there are two options:

1. Set the alpha value to 0
2. Quit Desktop Dimmer

None of those solutions are satisfying because:

1. Requires the user to reset the desired alpha value
2. Requires the user to reset the position of the slider (at least until #8 is resolved)

It would be nice to instead have an option in the menu to disable (and re-enable) Desktop Dimmer.

**Comment by sidneys** [comment]
@romainrichard 
Very good idea. Implemented in [v2.8.1](https://github.com/sidneys/desktop-dimmer/releases). Please test & post your feedback. Cheers.

**Comment by romainrichard** [comment]
It works, thanks for the quick implementation!
