### ISSUE TITLE
It doesn't work on "second level" windows or popups

### ISSUE THREAD

**Issue by gcjuan** [sidneys/desktop-dimmer#16]
## Current Behaviour

The whole desktop becomes darker but if you for example activate full screen mode on Firefox (F11), make a right click on the web browser (it appears the contextual menu), open a menu of a desktop application or click on a username entering field of a web form (it appears a list with the saved users) -I called these stuff "second level" windows or layers - , then they appear with the normal and actual monitor brightness as if desktop-dimmer has not influence over them.

It also occurs when pressing ALT+TAB or when activating the "Activities" mode on GNOME Shell (pressing the Windows key). These are also "second level" layers.

## 🎯 Expected Behaviour

All elements on the screen should stay darker.

## 👟 Steps to Reproduce (S2R)

One of the examples described above...

Whit desktop-dimmer running and the brightness adjusted at 50% (in order to notice the effect):
1. Open Firefox and a video on YouTube
2. Press F11 to activate the fullscreen mode.

## 🏡 Environmental Context

**App Version**
v 2.9.0
**Installation Type** 
Installed with the .deb package
**Operating System**
Ubuntu GNOME 16.04.2 ; Kernel: 4.10.5-041005-generic ; GNOME Shell 3.18.5

Images:

<a href='http://pix.toile-libre.org/?img=1490469837.png'><img src='http://pix.toile-libre.org/upload/thumb/1490469837.png' /></a>
<a href='http://pix.toile-libre.org/?img=1490469900.png'><img src='http://pix.toile-libre.org/upload/thumb/1490469900.png' /></a>
<a href='http://pix.toile-libre.org/?img=1490469960.png'><img src='http://pix.toile-libre.org/upload/thumb/1490469960.png' /></a>

**Comment by romainrichard** [comment]
Dup of #13

**Comment by xSeekTruthx** [comment]
Same issue on Ubuntu 14.04. Hope this will be fixed. Launcher icons are also massively bright.

**Comment by sidneys** [comment]
Thanks for your report.

The desired behaviour is currently not implementable via Electron - if this should change, i'll reopen this issue.

Cheers,
S
