### ISSUE TITLE
Clicking on icon should yield adjust brightness.

### ISSUE THREAD

**Issue by xSeekTruthx** [sidneys/desktop-dimmer#17]
## 🤷🏽‍♂️ Current Behaviour

Feature Suggestions: Click on sun icon in unity tool bar, asks if I want to "show desktop dimmer"

## 🎯 Expected Behaviour

Feature Suggestions: Click on sun icon in unity tool bar and automatically show brightness sliders without having to click on a drop down menu to retrieve it. 

I think it pretty obvious as to why I clicked on the icon, I want to change my brightness...

Just put version info in the brightness setting window, you already have the X there which quits the program.

**App Version**
v2.9.0
**Installation Type** 
amd64 deb
**Operating System**
Ubuntu 14.04 LTS

**Comment by sidneys** [comment]
Thanks for your reports. The desired behaviour is currently not implementable via Electron - if this should change, i'll reopen this issue.

Cheers,
S
