### ISSUE TITLE
Fullscreen metro apps, mouse cursor, taskbar, start menu, and context menus in Win32 apps are not dimmed

### ISSUE THREAD

**Issue by ajthemacboy** [sidneys/desktop-dimmer#19]
## 🤷🏽‍♂️ Current Behaviour

Fullscreen UWP/metro apps (such as Plex or Netflix), the mouse cursor, and right-click/context menus in Win32 programs (file Explorer, Chrome, Notepad, etc.) are not dimmed.

## 🎯 Expected Behaviour

All parts of Windows should be dimmed

## 👟 Steps to Reproduce (S2R)

- Run on Windows, open Explorer, and right click something
- Install the Netflix app from the Windows store, watch something, and go fullscreen
- Notice the taskbar becomes undimmed when you open the start menu, and that the start menu and cursor are undimmed

## 🏡 Environmental Context

**App Version**
2.9.0
**Installation Type** 
Setup
**Operating System**
Windows 10 Pro x64 build 1703

**Comment by sidneys** [comment]
Thanks for your report.

The desired behaviour is currently not implementable via Electron - if this should change, i'll reopen this issue.

Cheers,
S
