### ISSUE TITLE
Newest version can not run on  ubuntu 16.04

### ISSUE THREAD

**Issue by sudoyang** [sidneys/desktop-dimmer#2]
It is mentioned in this blog

http://www.omgubuntu.co.uk/2017/02/open-source-desktop-dimmer-app

![image](https://cloud.githubusercontent.com/assets/2531404/22755239/542e3c3c-ee10-11e6-8cc4-9102bbb5f315.png)

**Comment by Gabriel-p** [comment]
Very similar error shown in elementary OS Loki (based on Ubuntu 16.04, 64 bit)

![captura realizada el 2017-02-10 09 15 18](https://cloud.githubusercontent.com/assets/6054951/22826508/8a62eb7e-ef71-11e6-93e9-86bd2c88aa81.png)

Also, I can not exit the app via the 'Quit' menu. I get this:

![captura realizada el 2017-02-10 09 16 40](https://cloud.githubusercontent.com/assets/6054951/22826527/a83d4bc6-ef71-11e6-87e0-622b4a8d8d23.png)

**Comment by sidneys** [comment]
@sudoyang @Gabriel-p 
Thanks for the reports. The issue should be fixed with v2.5.0, please retest.

**Comment by romainrichard** [comment]
So far working fine on Ubuntu 16.04.2, thanks for the fix.

**Comment by Gabriel-p** [comment]
Working now. Not sure why there are two sliders though? They seem to have the same effect.

**Comment by sudoyang** [comment]
@sidneys Works! Thanks for the fix. 
@Gabriel-p I only have one slider. Try to remove old version first?
