### ISSUE TITLE
Dimming only occurs on one space per monitor

### ISSUE THREAD

**Issue by mrlife** [sidneys/desktop-dimmer#20]
## 🤷🏽‍♂️ Current Behaviour

Desktop Dimmer applies an overlay to the active space on each monitor.

## 🎯 Expected Behaviour

Desktop Dimmer applies an overlay to each space on each monitor. The menu bar dropdown would still have one slider for each monitor; a monitor's slider would adjust the overlays for all the spaces on that monitor.

## 👟 Steps to Reproduce (S2R)

 1. Open more than one desktop/space on one or more monitors
 2. Start Desktop Dimmer
 3. Switch to another desktop/space and notice there is no overlay/dimming

## 🏡 Environmental Context

**App Version**
v2.9.0
**Installation Type** 
Downloaded DMG from releases section
**Operating System**
MacOS 10.12.5 (16F73)

**Comment by sidneys** [comment]
@mrlife

Thanks for your report.

The desired behaviour is currently not implementable via Electron - if this should change, i'll reopen this issue.

Cheers,
S
