### ISSUE TITLE
Unable to scroll up or down in Microsoft Edge while dimmer is on

### ISSUE THREAD

**Issue by Anti-CCP** [sidneys/desktop-dimmer#23]
## 🤷🏽‍♂️ Current Behaviour

When I try to scroll up or down in Microsoft Edge with my cursor or my keyboard while dimmer is on, I am not able to scroll down, but when I pause or turn off dimmer, the scroll down function immediately works.

## 🎯 Expected Behaviour

Dimmer should not have conflict with scrolling up and down.

## 👟 Steps to Reproduce (S2R)

 1: Open Microsoft edge.
 2: Turn on dimmer
## 🏡 Environmental Context

**App Version**
v3.1.2
**Installation Type** 
Setup
**Operating System**
Windows 10 Pro x64 (15063.483)

**Comment by sidneys** [comment]
@Anti-CCP 

Thanks for the report. However, the issue could not be reproduced:  
![untitled](https://user-images.githubusercontent.com/1630917/32918466-ca197494-cb22-11e7-80a3-fd256cbeba06.gif)

Did you review this issue with the latest release?

Cheers,
s

**Comment by Anti-CCP** [comment]
Just tested with the latest release, the issue is patched now. Thx
