### ISSUE TITLE
Option to disable auto update

### ISSUE THREAD

**Issue by axtTOKQf** [sidneys/desktop-dimmer#26]
## 🤷🏽‍♂️ Current Behaviour

The software updates itself without any warn and I can't disable it.

## 🎯 Expected Behaviour

There should be an option to disable the auto-update. I am having a problem with the new version and trying to use the older one but it updates itself automatically.

## 🏡 Environmental Context

**Operating System**
Windows 10

**Comment by sidneys** [comment]
@axtTOKQf 

Thanks for your report. The feature has been added to the latest release:
https://github.com/sidneys/desktop-dimmer/releases

Please download & review.

Cheers,
S

**Comment by axtTOKQf** [comment]
Thank you!

**Comment by sidneys** [comment]
@axtTOKQf 

You're welcome ☺️
