### ISSUE TITLE
Linux 32bit RPM won't install on Fedora 25

### ISSUE THREAD

**Issue by progkix** [sidneys/desktop-dimmer#3]
Trying to install the 32bit RPM on Fedora 25 as follows:

rpm -ivh /strg/ftp/ibnd/DesktopDimmer-LnxX32-2.2.0.rpm
error: Failed dependencies:
	libappindicator1 is needed by desktop-dimmer-2.2.0-37.i386
	libgconf-2-4 is needed by desktop-dimmer-2.2.0-37.i386
	libnotify-bin is needed by desktop-dimmer-2.2.0-37.i386
	libnotify4 is needed by desktop-dimmer-2.2.0-37.i386

None of my searches have turned up anything for the missing dependencies.

Any ideas?

Thanks

**Comment by sidneys** [comment]
@progkix 
Thanks for the reports. Please re-test if the new rpm package in v2.5.0 works for you and comment.
