### ISSUE TITLE
Made with electron.

### ISSUE THREAD

**Issue by elethlad** [sidneys/desktop-dimmer#30]
hi i have a low spec pc with only i7 and 16gb memory, it eats too many memories and cpus. please fix

**Comment by sidneys** [comment]
@elethlad 

I'm also running i7 with 16Gs and can't reproduce your performance issues. Maybe install a RAM Doubler / Memory Booster app or upgrade to Windows ME?

Cheers,
S

**Comment by elethlad** [comment]
Okay so, I downloaded an upgrade from www.downloadmoreram.com and it really helped with those issues. Thanks for pointing me in the right direction. <3
