### ISSUE TITLE
Support for bottom task bars

### ISSUE THREAD

**Issue by hexion** [sidneys/desktop-dimmer#4]
The desktop dimmer window is always drawn in the upper right corner. This fits top menu bars but not menu bars placed at the bottom of the screen.

It is quite inconvenient to click on the menu icon and then go all the way up to move the bar. Support for bottom menu bars (via automatic detection if possible, or else through a configurable option) would be great.

**Comment by sidneys** [comment]
@hexion Thanks for the heads-up. However, we need more information about the environment (operating system, version) and the app (version, installation) for an assessment of the issue. Please add your "steps to reproduce". Cheers!

**Comment by hexion** [comment]
I'm running Ubuntu 16.04, with the gnome-flashback desktop environment.

I'm not sure right now if the menu bar is set to bottom by default, it might be at the top. To change it, press down Super+Alt+Right click on the menu bar, a menu will appear, select Properties. Then there is an option to change the layout.

As for reproducible steps, simply run the application on a system with a menu bar positioned at the bottom, and click on the app menu icon. The window with the sliding bar will appear at the top of the screen, far from the menu icon.

Thanks for looking into it.

**Comment by sidneys** [comment]
@hexion 
This issue was [recently](https://github.com/sidneys/desktop-dimmer/releases) resolved, but only tested on Windows. Please test and share your findings.

**Comment by hexion** [comment]
Clicking on the icon will now cause a stack trace:

Uncaught Exception:
TypeError: Cannot read property 'substr' of undefined
    at showWindow (/opt/Desktop Dimmer/resources/app.asar/node_modules/menubar/index.js:150:76)
    at Tray.clicked (/opt/Desktop Dimmer/resources/app.asar/node_modules/menubar/index.js:101:7)
    at emitTwo (events.js:106:13)
    at Tray.emit (events.js:191:7)

Hope that helps

**Comment by sidneys** [comment]
@hexion 
Thanks for the detailed logs. We tried a new approach which contains a workaround for the menu position (it is an upstream Electron issue) Linux.

Can you please test & share your findings from the latest release [v2.8.8](https://github.com/sidneys/desktop-dimmer/releases)?
Cheers.

**Comment by hexion** [comment]
Same stack trace upon click with version 2.8.8:

Uncaught Exception:
TypeError: Cannot read property 'substr' of undefined
    at showWindow (/opt/Desktop Dimmer/resources/app.asar/node_modules/menubar/index.js:150:76)
    at Tray.clicked (/opt/Desktop Dimmer/resources/app.asar/node_modules/menubar/index.js:101:7)
    at emitTwo (events.js:106:13)
    at Tray.emit (events.js:191:7)

Btw, I noticed this other enhancement request:
https://github.com/sidneys/desktop-dimmer/issues/8

IMHO, that would indirectly solve this issue. Sure, the app wouldn't automatically detect bottom task bars, but the user could just place it wherever he likes and as long as the window is drawn at the newly saved location, it would all be fine.

**Comment by sidneys** [comment]
@hexion 
Thanks for the quick test iterations. New version with changed menubar module is available: [v2.9.0](https://github.com/sidneys/desktop-dimmer/releases)
Keep the reports coming, this really is not reproducible on our test bed (Ubuntu 16.10, Unity 7)

**Comment by hexion** [comment]
No problem. With 2.9.0 there are no crashes. The popup window now has moved a bit to the left. It now shows up at the right top of the screen with an offset of about 200px to the left.

This may help. There is a command that can retrieve certain values for gnome-panel so, in environments that use it, will tell you where it is in the screen.

$ dconf read /org/gnome/gnome-panel/layout/toplevels/top-panel/orientation 
'bottom'
$ dconf read /org/gnome/gnome-panel/layout/toplevels/top-panel/size
24
$ dconf read /org/gnome/gnome-panel/layout/toplevels/top-panel/y
1056

The last 2 values are in pixels.

**Comment by sidneys** [comment]
Thanks for your reports. As the issue has been resolved, i'm closing this issue.

Please feel free to open a new issue if the issue should reoccur.

Cheers,
S
