### ISSUE TITLE
No menu icon in Ubuntu

### ISSUE THREAD

**Issue by probonopd** [sidneys/desktop-dimmer#6]
Launching the AppImage on Ubuntu 16.04 results in just a blinking cursor, with no visible user interface or menu item.

**Comment by sidneys** [comment]
@probonopd 
Thanks for the report. Does the app work as expected if you install the .deb package?

**Comment by probonopd** [comment]
Yes. It also installs 2 more debs:

```
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libindicator7 amd64
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 libappindicator1 amd64 
Fetched 40.7 kB in 0s (0 B/s)              
```

**Comment by sidneys** [comment]
@probonopd 
Thanks for the follow-up. This is the issue with the build system we are using (https://github.com/electron-userland/electron-builder/issues/1115). They seem to be working on this, so a local solution would only be incomplete and temporary.

Thus, for the time being, i will remove the AppImage builds in order not to confuse users with this. Thanks for the info!

**Comment by probonopd** [comment]
I don't actually think this is related to electron-userland/electron-builder#1115. I am talking about the notifications area in the menu bar in the upper-right hand corner of the screen, not the dock on the left-hand side of the screen.

**Comment by sidneys** [comment]
@probonopd 

Yes, thanks for the heads-up. This is the issue i think: https://github.com/electron-userland/electron-builder/issues/1082. The fix which supposedly was integrated in a version which broke other features (namely auto updating), which is why this project is using v11.5.1...
